stock_markets = {
    'nasdaq100': {
        'Apple Inc.': 'AAPL',
        'Microsoft Corporation': 'MSFT',
        'NVIDIA Corporation': 'NVDA',
        'Amazon.com Inc.': 'AMZN',
        'Meta Platforms Inc.': 'META',
        'Alphabet Inc. Class A': 'GOOGL',
        'Alphabet Inc. Class C': 'GOOG',
        'Tesla Inc.': 'TSLA',
        'Broadcom Inc.': 'AVGO',
        'PepsiCo Inc.': 'PEP',
        'Costco Wholesale Corporation': 'COST',
        'Adobe Inc.': 'ADBE',
        'Cisco Systems Inc.': 'CSCO',
        'Netflix Inc.': 'NFLX',
        'Comcast Corporation': 'CMCSA',
        'Advanced Micro Devices Inc.': 'AMD',
        'T-Mobile US Inc.': 'TMUS',
        'Intel Corporation': 'INTC',
        'Qualcomm Inc.': 'QCOM',
        'Texas Instruments Inc.': 'TXN',
        'Starbucks Corporation': 'SBUX',
        'Honeywell International Inc.': 'HON',
        'Intuit Inc.': 'INTU',
        'Amgen Inc.': 'AMGN',
        'PayPal Holdings Inc.': 'PYPL',
        'Applied Materials Inc.': 'AMAT',
        'Booking Holdings Inc.': 'BKNG',
        'Automatic Data Processing Inc.': 'ADP',
        'Mondelez International Inc.': 'MDLZ',
        'Gilead Sciences Inc.': 'GILD',
        'Vertex Pharmaceuticals Inc.': 'VRTX',
        'Lam Research Corporation': 'LRCX',
        'Regeneron Pharmaceuticals Inc.': 'REGN',
        'Analog Devices Inc.': 'ADI',
        'Micron Technology Inc.': 'MU',
        'CSX Corporation': 'CSX',
        'Charter Communications Inc.': 'CHTR',
        'Moderna Inc.': 'MRNA',
        'Marriott International Inc.': 'MAR',
        'Monster Beverage Corporation': 'MNST',
        'Synopsys Inc.': 'SNPS',
        'Cadence Design Systems Inc.': 'CDNS',
        'Kraft Heinz Company': 'KHC',
        'Fiserv Inc.': 'FI',
        'O\'Reilly Automotive Inc.': 'ORLY',
        # 'Activision Blizzard Inc.': 'ATVI', Activision Blizzard (ATVI) è stata quotata al NASDAQ fino a ottobre 2023, quando è stata acquisita da Microsoft.
        'Palo Alto Networks Inc.': 'PANW',
        'ASML Holding NV': 'ASML',
        'Intuitive Surgical Inc.': 'ISRG',
        'Keurig Dr Pepper Inc.': 'KDP',
        'Airbnb Inc.': 'ABNB',
        'MercadoLibre Inc.': 'MELI',
        'KLA Corporation': 'KLAC',
        'Ross Stores Inc.': 'ROST',
        'Fortinet Inc.': 'FTNT',
        'PACCAR Inc.': 'PCAR',
        'Workday Inc.': 'WDAY',
        'Paychex Inc.': 'PAYX',
        'Dexcom Inc.': 'DXCM',
        'Sirius XM Holdings Inc.': 'SIRI',
        'Electronic Arts Inc.': 'EA',
        'Align Technology Inc.': 'ALGN',
        'Autodesk Inc.': 'ADSK',
        'Illumina Inc.': 'ILMN',
        'Datadog Inc.': 'DDOG',
        'Dollar Tree Inc.': 'DLTR',
        'Biogen Inc.': 'BIIB',
        'Zscaler Inc.': 'ZS',
        'Marvell Technology Inc.': 'MRVL',
        'Lucid Group Inc.': 'LCID',
        'Crowdstrike Holdings Inc.': 'CRWD',
        'eBay Inc.': 'EBAY',
        'Warner Bros Discovery Inc.': 'WBD',
        'JD.com Inc.': 'JD',
        'Zoom Video Communications Inc.': 'ZM',
        'Cognizant Technology Solutions Corp.': 'CTSH',
        # 'Pinduoduo Inc.': 'PDD',
        'CoStar Group Inc.': 'CSGP',
        'Atlassian Corporation': 'TEAM',
        'Baker Hughes Company': 'BKR',
        'Rivian Automotive Inc.': 'RIVN',
        'Fastenal Company': 'FAST',
        'Enphase Energy Inc.': 'ENPH',
        'Constellation Energy Corporation': 'CEG',
        # 'Chesapeake Energy Corporation': 'CHK', rimossa perché quotata dal 2021 dopo la bancarotta. Porta eccezioni nel codice che non ha senso gestire ora per via dell'approssimazione di questo algoritmo
        'American Electric Power Company Inc.': 'AEP',
        'Xcel Energy Inc.': 'XEL',
        'Exelon Corporation': 'EXC',
        'The Trade Desk Inc.': 'TTD',
        'Lululemon Athletica Inc.': 'LULU',
        'Verisk Analytics Inc.': 'VRSK',
        'Diamondback Energy Inc.': 'FANG',
        'Microchip Technology Inc.': 'MCHP',
        # 'Splunk Inc.': 'SPLK', Splunk (SPLK) è stata quotata al NASDAQ dal 2012 fino al 2024, quando è stata acquisita da Cisco Systems.
        'Copart Inc.': 'CPRT',
        'Cintas Corporation': 'CTAS',
        'CDW Corporation': 'CDW',
        'Okta Inc.': 'OKTA',
        'GlobalFoundries Inc.': 'GFS',
        'Walgreens Boots Alliance Inc.': 'WBA',
        'ON Semiconductor Corporation': 'ON',
        'Old Dominion Freight Line Inc.': 'ODFL',
        'Celsius Holdings Inc.': 'CELH'
    },
    'nyse100': {
        'JPMorgan Chase & Co.': 'JPM',
        'Visa Inc.': 'V',
        'Mastercard Incorporated': 'MA',
        'UnitedHealth Group Inc.': 'UNH',
        'Johnson & Johnson': 'JNJ',
        'Procter & Gamble Co.': 'PG',
        'Exxon Mobil Corporation': 'XOM',
        'Bank of America Corp.': 'BAC',
        'Chevron Corporation': 'CVX',
        'Walmart Inc.': 'WMT',
        'Pfizer Inc.': 'PFE',
        'The Home Depot Inc.': 'HD',
        'Coca-Cola Company': 'KO',
        'Merck & Co. Inc.': 'MRK',
        'AbbVie Inc.': 'ABBV',
        'McDonald\'s Corporation': 'MCD',
        'Abbott Laboratories': 'ABT',
        'Wells Fargo & Co.': 'WFC',
        'Thermo Fisher Scientific Inc.': 'TMO',
        'Accenture plc': 'ACN',
        'Morgan Stanley': 'MS',
        'Bristol-Myers Squibb Co.': 'BMY',
        'Elevance Health Inc.': 'ELV',
        'The Boeing Company': 'BA',
        'United Parcel Service Inc.': 'UPS',
        'NIKE Inc.': 'NKE',
        'Caterpillar Inc.': 'CAT',
        'The Goldman Sachs Group Inc.': 'GS',
        'Union Pacific Corporation': 'UNP',
        'BlackRock Inc.': 'BLK',
        'Linde plc': 'LIN',
        'American Express Company': 'AXP',
        'Citigroup Inc.': 'C',
        'CVS Health Corporation': 'CVS',
        'Eli Lilly and Company': 'LLY',
        'Raytheon Technologies Corp.': 'RTX',
        'NextEra Energy Inc.': 'NEE',
        'The Walt Disney Company': 'DIS',
        '3M Company': 'MMM',
        'AT&T Inc.': 'T',
        'International Business Machines Corp.': 'IBM',
        'General Electric Company': 'GE',
        'ConocoPhillips': 'COP',
        'Duke Energy Corporation': 'DUK',
        'Deere & Company': 'DE',
        'Lockheed Martin Corporation': 'LMT',
        'ServiceNow Inc.': 'NOW',
        'General Motors Company': 'GM',
        'The Southern Company': 'SO',
        'U.S. Bancorp': 'USB',
        'American Tower Corporation': 'AMT',
        'The Charles Schwab Corporation': 'SCHW',
        'Target Corporation': 'TGT',
        'Schlumberger Limited': 'SLB',
        'Northrop Grumman Corporation': 'NOC',
        'EOG Resources Inc.': 'EOG',
        'Crown Castle International Corp.': 'CCI',
        'The TJX Companies Inc.': 'TJX',
        'Marsh & McLennan Companies Inc.': 'MMC',
        'Norfolk Southern Corporation': 'NSC',
        'General Dynamics Corporation': 'GD',
        'MetLife Inc.': 'MET',
        'Phillips 66': 'PSX',
        'The Sherwin-Williams Company': 'SHW',
        'Dominion Energy Inc.': 'D',
        'Emerson Electric Co.': 'EMR',
        'Marathon Petroleum Corporation': 'MPC',
        'The Kraft Heinz Company': 'KHC',
        'FedEx Corporation': 'FDX',
        'Truist Financial Corporation': 'TFC',
        'Valero Energy Corporation': 'VLO',
        'Ford Motor Company': 'F',
        'Capital One Financial Corporation': 'COF',
        'The Blackstone Group Inc.': 'BX',
        'CME Group Inc.': 'CME',
        'Pioneer Natural Resources Company': 'PXD',
        'Marathon Oil Corporation': 'MRO',
        'Occidental Petroleum Corporation': 'OXY',
        'The Bank of New York Mellon Corp.': 'BK',
        'DuPont de Nemours Inc.': 'DD',
        'Dow Inc.': 'DOW',
        'The Travelers Companies Inc.': 'TRV',
        'Johnson Controls International plc': 'JCI',
        'Delta Air Lines Inc.': 'DAL',
        'American Airlines Group Inc.': 'AAL',
        'United Airlines Holdings Inc.': 'UAL',
        'Halliburton Company': 'HAL',
        'The Mosaic Company': 'MOS',
        'CF Industries Holdings Inc.': 'CF',
        'Devon Energy Corporation': 'DVN',
        'The Williams Companies Inc.': 'WMB',
        'Archer-Daniels-Midland Company': 'ADM',
        'Enterprise Products Partners L.P.': 'EPD',
        'Kinder Morgan Inc.': 'KMI',
        'FirstEnergy Corp.': 'FE',
        'ONEOK Inc.': 'OKE',
        'Public Service Enterprise Group Inc.': 'PEG',
        'DTE Energy Company': 'DTE',
        'Consolidated Edison Inc.': 'ED',
        'Sempra Energy': 'SRE',
        'The AES Corporation': 'AES',
        'WEC Energy Group Inc.': 'WEC',
        'Eversource Energy': 'ES',
        'NiSource Inc.': 'NI',
        'CenterPoint Energy Inc.': 'CNP'
    }
}